---
version: "2.0"

services:
  broadway:
    image: ghcr.io/aktdenis/broadway:latest
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - AKASH_API_KEY=
      - GITHUB_TOKEN=
      - WEBHOOK_SECRET=
      - DEPLOY_TOKEN=
      - STORE_PATH=/data/deployments.json
      - NODE_ENV=production
      - BROADWAY_DOMAIN=akash.world
      - MAX_PREVIEWS=8
      - EXCLUDE_PROVIDERS=akash1ek2p65eg2c8sgge3m04e9af00lppzsg3v6xx0x,akash1k94uya5rhrtj9rfw850az9aq2d6vdpjmtnlgd0,akash15tl6v6gd0nte0syyxnv57zmmspgju4c3xfmdhk
      - PREFER_PROVIDER=
    params:
      storage:
        data:
          mount: /data

profiles:
  compute:
    broadway:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
          - name: data
            size: 1Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        broadway:
          denom: uusd
          amount: 1000

deployment:
  broadway:
    dcloud:
      profile: broadway
      count: 1
